name: compile-code

on: [push, pull_request]

jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - name: check it out
        uses: actions/checkout@v4
      - name: Run the build script
        run: |
          cd Lotto
          make
          ./lotto

